// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_codonSplitCpp
std::vector<std::string> cpp_codonSplitCpp(std::string cDNA);
RcppExport SEXP _rptPlus_cpp_codonSplitCpp(SEXP cDNASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type cDNA(cDNASEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_codonSplitCpp(cDNA));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rptPlus_cpp_codonSplitCpp", (DL_FUNC) &_rptPlus_cpp_codonSplitCpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rptPlus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
