# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Split a string into codons
#'
#' @param cDNA A string.
#' @export
cpp_codonSplitCpp <- function(cDNA) {
    .Call('_rptPlus_cpp_codonSplitCpp', PACKAGE = 'rptPlus', cDNA)
}

